minPupilSizeLLzscore={zeros(length(LL1),3),...
    zeros(length(LL2),3),...
    zeros(length(LL3),3),...
    zeros(length(LL4),3),...
    zeros(length(LL5),3)};
minPupilTimeLL={zeros(length(LL1),3),...
    zeros(length(LL2),3),...
    zeros(length(LL3),3),...
    zeros(length(LL4),3),...
    zeros(length(LL5),3)};
goodPupils={LL1,LL2,LL3,LL4,LL5};
for light=1:5
    pupil=goodPupils{light};
    for animal=1:size(pupil.allmeanZscores,1)
        [sizes,time]=min(pupil.allmeanZscores(animal,:,:));
        minPupilSizeLLzscore{light}(animal,:)=sizes;
        minPupilTimeLL{light}(animal,:)=time;
    end
end
